# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Art of Code
description: > # this means to ignore newlines until "baseurl:"
  Art of Code homepage
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://artofcode.co" # the base hostname & protocol for your site
twitter_username: artofcode_co
github_username:  artofcodelabs

# Build settings
markdown: kramdown

exclude:
  - node_modules